### ISSUE TITLE
Serial.printf has no effect

### ISSUE THREAD

**Issue by yoursunny** [Wiz-IO/platform-azure#1]
Host: Windows 10 Home, PIO Core 4.0.2, platform-azure c6b6adfb7cdbf5626b170f06d233f23f8234bef5
Device: AES-MS-MT3620-SK-G
Program: ArduinoAzureBlink example

Expected: `platformio.exe device monitor` should display serial messages such as "Arduino - Hello World - PlatformIO" and "Loop".
Actual: device monitor shows "[PLUTON] Booting application core" from bootloader, no more message after that

I also tried changing `Serial.printf` to [Log_Debug](https://docs.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-log/function-log-debug), but it has the same result.

**Comment by Wiz-IO** [comment]
Hi
Open project platformio.ini and paste/edit
monitor_port = COMx
monitor_speed = 115200

**Comment by Wiz-IO** [comment]
Edit: Serial & Serial1 is real board uarts
https://github.com/Wiz-IO/framework-azure/blob/783b1effeee9e36aececdbb03b1dfdd376c816be/arduino/variants/avnet_aesms_mt3620/variant.cpp#L9

I dont know how to use Log_Debug() without Visual Studio...

**Comment by yoursunny** [comment]
> monitor_port = COMx
> monitor_speed = 115200

These are already in place in the example, and they should be correct or "[PLUTON] Booting application core" message would not appear.

**Comment by Wiz-IO** [comment]
monitor_port = COM6 is manual selection of monitor port for me
Serial is microBUS 2 - ISU0 RX/TX pinouts 
( page 11 )
https://www.avnet.com/opasdata/d120001/medias/docus/196/Azure%20Sphere%20Starter%20Kit%20User%20Guide%20(v1.3).pdf

**Comment by Wiz-IO** [comment]
for Log_Debug()
you need use Terminal program and gdb at 192.168.35.2:2342
https://docs.microsoft.com/en-us/azure-sphere/app-development/manual-build#sideload-and-debug
