### ISSUE TITLE
Communicate M4 & M7 issues

### ISSUE THREAD

**Issue by Robertou2** [Wiz-IO/platform-azure#2]
I am trying to communicate M4 and M7 cores, and I find 2 issues:
- The component ID change everytime  the code is uploaded to the board, and the number it is not the same as the one in componentID from app_manifest.json.
- Everytime I upload a new application it removes all the applications installed in the board. I use Visual Code to upload different components .

> Checking size .pio\build\avnet_aesms_mt3620\app.elf
> Packing image...
> UUID:  32A2E119-5699-448B-98AA-C8832C2E1876 
> Memory Usage -> http://bit.ly/pio-memory-usage
> DATA:    [          ]   0.9% (used 2272 bytes from 262144 bytes)
> PROGRAM: [          ]   2.9% (used 30512 bytes from 1048576 bytes)
> Command completed successfully in 00:00:00.9302438.
> 
> Configuring upload protocol...
> 
> 
> Component '8548b129-b16f-4f84-8dbe-d2c847862e78' deleted or was not present beforehand.
> Component '685f13af-25a5-40b2-8dd8-8cbc253ecbd8' deleted or was not present beforehand.
> Component '005180bc-402f-4cb3-a662-72937dbcde47' deleted or was not present beforehand.
> Command completed successfully in 00:00:04.3563300.
> 
> OLD APPLICATION IS REMOVED
> Deploying 'c:/Users/rober/proyectos/pruebasphere/.pio/build/avnet_aesms_mt3620\app.image' to the attached device.
> warn: This app targets Beta APIs that may change or be removed in future.
> Image package 'c:/Users/rober/proyectos/pruebasphere/.pio/build/avnet_aesms_mt3620\app.image' has been deployed to the attached device.
> Command completed successfully in 00:00:06.9794264.
> 
> NEW APPLICATION IS READY**

**Comment by Wiz-IO** [comment]
Hi,
Microsoft documentation not have info about applications uploading ( deploy ), only this page
https://docs.microsoft.com/en-us/azure-sphere/app-development/manual-build

PlatformIO not have UI buttons for ... Delete Current, Delete All...
I can insert only settings in platformio.ini about app removing

About GUID I can generate only one for project...

If you have ideas....

**Comment by Robertou2** [comment]
Hi,
for the GUID, maybe it is better not to run the uuidgen when you upload a component, Maybe it is better to run it outside of platformio and copy the result in app_manifest.json. 

The same with the upload o new programms, maybe it is better that Platformio upload the new component and if you need to delete programs you do it with the azure sphere tools.

What do you think?

**Comment by Wiz-IO** [comment]
For GUID I use python function...
And packer use this GUID to generate component id

This days will test any ideas

**Comment by Robertou2** [comment]
Hi,
for testing I have change common.py.
UIID = "005180bc-402f-4cb3-a662-72937dbcde47"
And I add this two lines in the delete section, so now I only delete the actual application
cmd.append("-i")
cmd.append("005180bc-402f-4cb3-a662-72937dbcde47")

And everything is working, I have a modified version of your M4 application with analogRead(0) , and the M7 application from the advanced tutorial.
Next week I try to use the modified version of the OLED example to receive the messages from M4 in the M7 core.

**Comment by Wiz-IO** [comment]
ok, I will create GUID as "template file" in project folder
if file exist - use this GUID, if not exist create new... something like that
