### ISSUE TITLE
Setup Clarity

### ISSUE THREAD

**Issue by techguyzz** [Wiz-IO/platform-azure#4]
H Wiz,

Am just curious on following items.
1. Does the Azure Sphere is re-flashed with custom software
2. How Aurdino is used along with the base Sphere board
3. Does the security still valid as given by MSFT

**Comment by Wiz-IO** [comment]
Hi
1. There is no custom software for "service" ... except MS
2. as normal Arduino .... the Arduino is just one C++ library, nothing else,
but makes things easier for the average user
3. 100% valid ...

**Comment by techguyzz** [comment]
Hi,
Sorry, Still am not clear.

As such azure sphere is a device with MSFT software flashed over Mediatek platform. 
Here please specify what is the role of Arduino board ?
I can understand that Azure sphere can run apps flashed from Windows machine but not clear what you are doing with Arduino board here.

**Comment by Wiz-IO** [comment]
the Sphere is a custom Linux for MT3620 SoC
I not use other Arduino board .... I make Azure Sphere as Arduino board
Arduino app is executed inside the Sphere
