### ISSUE TITLE
No COM6

### ISSUE THREAD

**Issue by BlackXDragon** [Wiz-IO/platform-azure#7]
My Azure Sphere shows only 3 COM ports (COM5, COM7, COM8). Please help me figure out how to get COM6.

**Comment by Wiz-IO** [comment]
Hi
COM6 from examples INI file ?
On my PC upload port is COM6...
Just re-edit this local project INI file with your COM port number

**Comment by BlackXDragon** [comment]
Thanks for your reply!

I've tried using all 3 available COM ports, but no luck. Should the Azure Sphere have a total of 3 COM ports or 4?

For me, COM5 doesn't display anything. COM7 access is restricted (not accessible even as admin, for some reason). COM8 display some system logs such as OS booting, etc.

**Comment by Wiz-IO** [comment]
test what is Uploading port
one is service port, one is "loger", other is uploading port

**Comment by BlackXDragon** [comment]
How can I figure that out?

**Comment by Wiz-IO** [comment]
three times: edit INI - COMx - Upload

**Comment by BlackXDragon** [comment]
Ok, I'll do that and get back to you!

**Comment by BlackXDragon** [comment]
The following are what I got for each port:

COM5 displayed literally nothing.

COM7:
`could not open port 'COM7': could not open port 'COM7': PermissionError(13, 'Access is denied.', None, 5)`

COM8:
`[1BL] BOOT: 70e00000/00000000/01000000
G=2051af077579a396b4cfd5215d416026fbfb71cc2b38111797ff5b93f3c71329c04f710a98aa1dd573efe47f26ccdf7b774c98bf0667d6e0b6649fe3bf608cda
D=19299ad883af3c93dd453c4aa7f045cd6ef7e66eb7311163fe3419cef9b82e960ff66cafa6aae10edd2529b300e89b92f0adc9c20ae6187a366c0c2b165d2ed8,N=4f0b392f86b4ca05ac50c0f70eb8b2419ff572cba9a737ddba98422c53ffd7bf
[PLUTON] Logging initialized
[PLUTON] Booting HLOS core`

**Comment by Wiz-IO** [comment]
maybe not work your Azure Sphere Device Communication Service or TAP driver
https://github.com/Wiz-IO/platform-azure/wiki/Install-Notes

Visual studio work with Azure Sphere module?

**Comment by BlackXDragon** [comment]
Thanks, I'll check!

**Comment by BlackXDragon** [comment]
Hey, since I'm an absolute beginner with the Azure Sphere right now, could you tell me if I should be seeing output of Serial.println on my computer through a COM port or on a UART port exposed through some pins?

**Comment by Wiz-IO** [comment]
USB-COMa,b,c is "service" ports only as ... upload

Serial... use physical SoC UARTs - just find RX/TX PINs on board and connect with PC

**Comment by Wiz-IO** [comment]
https://www.avnet.com/opasdata/d120001/medias/docus/196/Azure%20Sphere%20Starter%20Kit%20User%20Guide%20(v1.3).pdf

page 11 - look "MicroBUS - Click modules 1 & 2" pinouts

**Comment by Wiz-IO** [comment]
example: for Serial
https://github.com/Wiz-IO/platform-azure/blob/master/Examples/ArduinoAzureBlink/src/main.cpp#L11
and in app_manifest.json 
https://github.com/Wiz-IO/platform-azure/blob/master/Examples/ArduinoAzureBlink/src/app_manifest.json#L12
"**enable**" UART Capabilities

**Comment by BlackXDragon** [comment]
Oh, thanks a lot!! I was thinking that Serial prints out through a COM port like regular Arduino boards!

Thanks a lot for the clarification!
